<?xml version="1.0"?>
<package format="3">
  <name>robot_control</name>
  <version>0.1.0</version>
  <description>ros2_control bringup for TurtleBot diff drive.</description>
  <maintainer email="dev@example.com">robotsim</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>controller_manager</exec_depend>
  <exec_depend>diff_drive_controller</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
</package>
